server:
  port: 7777

invoicing-system:
  database:
    directory: db
    type: file
    file:
      id: id.txt
      invoices: invoices.txt

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: false
