server:
  port: 7777

invoicing-system:
  database:
    directory: db
    type: file
    file:
      companyId: companyId.txt
      invoiceId: invoiceId.txt
      invoices: invoices.txt
      companies: companies.txt

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

profiles:
  active: sql
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    baseline-on-migrate: true
    enabled: true
