server:
  port: 7777

invoicing-system:
  database:
    directory: db
    type: file
    file:
      id: id.txt
      invoices: invoices.txt

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: WARN
        invoicing.db: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher