server:
  port: 7777

invoicing-system:
  database:
    type: memory

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    baseline-on-migrate: true
    enabled: true