server:
  port: 9999

invoicing-system:
  database:
    directory: db
    type: file
    file:
      id: id.txt
      invoices: invoices.txt

profiles:
spring:
  active: file
  flyway:
    enabled: false