server:
  port: 9999

invoicing-system:
  database:
    directory: db
    type: file
    file:
      companyId: companyId.txt
      invoiceId: invoiceId.txt
      invoices: invoices.txt
      companies: companies.txt

profiles:
spring:
  active: file
  flyway:
    enabled: false