invoicing-system:
  database:
    type: jpa

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/invoices-jpa
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver