server:
  port: 7777

invoicing-system:
  database:
    directory: db
    type: sql
    file:
      id: id.txt
      invoices: invoices.txt

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    baseline-on-migrate: true
    enabled: true
