package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Invoice {

  @ApiModelProperty(value = "Invoice id (generated by application)", required = true, example = "1")
  private int id;

  @ApiModelProperty(value = "Creation date", required = true, example = "2023-07-25")
  private LocalDate date;

  @ApiModelProperty(value = "Buyer company", required = true, example = "DODAć")
  private Company buyer;

  @ApiModelProperty(value = "Seller company", required = true)
  private Company seller;

  @ApiModelProperty(value = "List of invoice entries", required = true)
  private List<InvoiceEntry> entries;
}
