package pl.futurecollars.invoicing.model;

import static javax.persistence.CascadeType.ALL;

import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Invoice id (generated by application", required = true)
    private long id;
    @ApiModelProperty(value = "Invoice number (assigned by user)", required = true, example = "2023/06/15/0001")
    private String number;
    @ApiModelProperty(value = "Invoice creation date", required = true, example = "2023-06-15")
    private LocalDate date;
    @JoinColumn(name = "buyer")
    @OneToOne(cascade = ALL, orphanRemoval = true)
    @ApiModelProperty(value = "Buyer company", required = true)
    private Company buyer;
    @JoinColumn(name = "seller")
    @OneToOne(cascade = ALL, orphanRemoval = true)
    @ApiModelProperty(value = "Seller company", required = true)
    private Company seller;
    @OneToMany(cascade = ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JoinTable(name = "invoice_invoice_entry",
        joinColumns = {@JoinColumn(name = "invoice_id")},
        inverseJoinColumns = {@JoinColumn(name = "invoice_entry_id")})
    @ApiModelProperty(value = "List of invoice entries", required = true)
    private List<InvoiceEntry> entries;
}
