name: CI

on:
  push:
    branches: [ 'task_*/.*', 'master' ]
  pull_request:
    branches: [ 'task_*/.*', 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
           mongodb-version: 4.4

      - name: Mark gradlew as executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: build/reports/**