name: CI

on:
  push:
    branches: [ 'task_*/.*', 'master' ]
  pull_request:
    branches: [ 'task_*/.*', 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Mark gradlew as executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build